version: '3.1'
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: always
    volumes:
    - ./pgsql:/var/lib/postgresql/data
    
    environment:
      - 'TZ=America/Fortaleza'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=redmine'
  redmine:
    image: redmine:4.1.1
    container_name: redmine

    links:
    - postgres:postgres
    depends_on:
    - postgres

    restart: always
    volumes:
    - ./redmine:/usr/src/redmine/files

    ports:
      - 80:3000
    environment:      
      - 'REDMINE_DB_POSTGRES=postgres'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=password'