version: '3.1'
services:
  db-redmine:
    image: postgres:12-alpine
    container_name: redmine-pgsql
    restart: always
    volumes:
    - ./pgsql:/var/lib/postgresql/data    
    environment:
      - 'TZ=America/Fortaleza'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=redmine'
  redmine:
    image: redmine:4.1.1
    container_name: redmine
    links:
    - db-redmine:redmine-pgsql
    depends_on:
    - db-redmine
    restart: always
    volumes:
    - ./redmine:/usr/src/redmine/files
    ports:
      - 80:3000
    environment:      
      - 'REDMINE_DB_POSTGRES=db-redmine'
      - 'REDMINE_DB_DATABASE=redmine'
      - 'REDMINE_DB_PASSWORD=password'